project:
  type: website

website:
  title: "Données émergentes"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Introduction"
        file: introduction.qmd
      - text: "Données administratives"
        menu:
          - administratives.qmd
          - administratives_exemples.qmd
      - text: "Données géolocalisées"
        menu: 
          - geolocalized_data.qmd
          - geolocalized_data_exemples.qmd
          - applications/application1.qmd
      - text: "Analyse textuelle"
        menu:
          - textes.qmd
          - applications/ape.qmd
          - textes_exemples.qmd
      - text: "Analyse d'images"
        menu:
          - images.qmd
          - images_exemples.qmd
      - text: "Nowcasting"
        menu:
          - series_temporelles.qmd
          - nowcasting_exemples.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Introduction"
        contents:
          - introduction.qmd
      - section: "Données administratives"
        contents:
          - administratives.qmd
          - administratives_exemples.qmd
      - section: "Données géolocalisées"
        contents:
          - geolocalized_data.qmd
          - geolocalized_data_exemples.qmd
          - applications/application1.qmd
      - section: "Analyse textuelle"
        contents:
          - textes.qmd
          - applications/ape.qmd
          - textes_exemples.qmd
      - section: "Analyse d'images"
        contents:
          - images.qmd
          - images_exemples.qmd
      - section: "Nowcasting"
        contents:
          - series_temporelles.qmd
          - nowcasting_exemples.qmd
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/InseeFrLab/cours-nouvelles-donnees-site
          - text: Report a Bug
            url: https://github.com/InseeFrLab/cours-nouvelles-donnees-site/issues
  page-navigation: true
  page-footer:
    left: "(c) 2022, Lino Galiana and Tom Seimandi"
    right:
      - icon: github
        href: https://github.com/InseeFrLab/cours-nouvelles-donnees-site
  reader-mode: true
  repo-url: https://github.com/InseeFrLab/cours-nouvelles-donnees-site
  repo-actions: [edit, issue]
  twitter-card:
    creator: "@linogaliana"
  open-graph: true


bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

theme:
  light: [flatly, custom.scss]
  dark: [darkly, custom.scss]


filters:
  #- black-formatter
  - build/callout-vscode.lua
  #- include-code-files
